load:
  type: constant
  stages:
  - rate: 2
    duration: 30
api: 
  type: completion
  streaming: true
server:
  type: vllm
  model_name: meta-llama/Meta-Llama-3-8B
  base_url: http://localhost:8005
  ignore_eos: true
tokenizer:
  pretrained_model_name_or_path: meta-llama/Meta-Llama-3-8B
data:
  type: random
  input_distribution:
    min: 128
    max: 1024
    mean: 512
    type: uniform
  output_distribution:
    min: 16
    max: 256
    mean: 128
    type: uniform
report:
  request_lifecycle:
    summary: true
    per_stage: true
