apiVersion: v1
kind: Service
metadata:
  labels:
    app: gemma4-vllm-vllm-inference-server
  name: gemma4-vllm-vllm-service
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: gemma4-vllm-vllm-inference-server
    deployment: gemma4-vllm-vllm-deployment
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gemma4-vllm-vllm-inference-server
  name: gemma4-vllm-vllm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gemma4-vllm-vllm-inference-server
      deployment: gemma4-vllm-vllm-deployment
  template:
    metadata:
      labels:
        ai.gke.io/inference-server: vllm
        ai.gke.io/model: gemma4-vllm
        app: gemma4-vllm-vllm-inference-server
        deployment: gemma4-vllm-vllm-deployment
        examples.ai.gke.io/source: blueprints
    spec:
      containers:
      - args:
        - --model=$(MODEL_ID)
        - --tensor-parallel-size=$(TENSOR_PARALLEL_SIZE)
        command:
        - python3
        - -m
        - vllm.entrypoints.openai.api_server
        env:
        - name: MODEL_ID
          value: google/gemma-2b
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: hf_api_token
              name: hf-secret
        - name: TENSOR_PARALLEL_SIZE
          value: "1"
        image: vllm/vllm-openai:latest
        name: inference-server
        ports:
        - containerPort: 8000
          name: metrics
        readinessProbe:
          failureThreshold: 60
          httpGet:
            path: /health
            port: 8000
          periodSeconds: 10
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-rtx-pro-6000
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
