apiVersion: apps/v1
kind: Deployment
metadata:
  name: '*'
spec:
  template:
    metadata:
      labels:
        ai.gke.io/model: gemma-7b-it
        ai.gke.io/inference-server: vllm
    spec:
      containers:
      - name: inference-server
        image: vllm/vllm-openai:v0.6.6
        args:
        - --model=$(MODEL_ID)
        - --device=cpu
        env:
        - name: VLLM_TARGET_DEVICE
          value: cpu
        resources:
          requests:
            cpu: "4"
            memory: "32Gi"
          limits:
            cpu: "8"
            memory: "64Gi"
        readinessProbe:
          failureThreshold: 120
          httpGet:
            path: /health
            port: 8000
          periodSeconds: 10
