apiVersion: v1
kind: Service
metadata:
  labels:
    app: llama3-8b-vllm-inference-server
  name: llama3-8b-vllm-service-cpu
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: llama3-8b-vllm-inference-server
    deployment: llama3-8b-vllm-deployment
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: llama3-8b-vllm-inference-server
  name: llama3-8b-vllm-deployment-cpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama3-8b-vllm-inference-server
      deployment: llama3-8b-vllm-deployment
  template:
    metadata:
      labels:
        ai.gke.io/inference-server: vllm
        ai.gke.io/model: llama3-8b
        app: llama3-8b-vllm-inference-server
        deployment: llama3-8b-vllm-deployment
    spec:
      containers:
      - args:
        - --model=$(MODEL_ID)
        - --device=cpu
        command:
        - python3
        - -m
        - vllm.entrypoints.openai.api_server
        env:
        - name: MODEL_ID
          value: meta-llama/Meta-Llama-3-8B
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              key: hf_api_token
              name: hf-secret
        image: vllm/vllm-openai:latest
        name: inference-server
        ports:
        - containerPort: 8000
          name: metrics
        readinessProbe:
          failureThreshold: 120
          httpGet:
            path: /health
            port: 8000
          periodSeconds: 10
        resources:
          limits:
            cpu: "8"
            memory: 32Gi
          requests:
            cpu: "4"
            memory: 16Gi
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
