apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gemma4-vllm-vllm-inference-server
  name: gemma4-vllm-vllm-deployment
spec:
  selector:
    matchLabels:
      app: gemma4-vllm-vllm-inference-server
      deployment: gemma4-vllm-vllm-deployment
  template:
    metadata:
      labels:
        app: gemma4-vllm-vllm-inference-server
        deployment: gemma4-vllm-vllm-deployment
    spec:
      containers:
      - name: inference-server
        env:
          - name: MODEL_ID
            value: google/gemma-2b
