apiVersion: v1
kind: Service
metadata:
  name: gemma4-vllm-vllm-service
  labels:
    app: gemma4-vllm-vllm-inference-server 
spec:
  selector:
    app: gemma4-vllm-vllm-inference-server
    deployment: gemma4-vllm-vllm-deployment
